version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: emojigen/node-py23:node11.1.0-py2.7.15-py3.7.0
    environment:
      GIT_TERMINAL_PROMPT: 0
      TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule update --init --recursive --jobs=6
      - run:
          name: System information
          command: |
            python2 --version
            python3 --version | head -1
            echo "Node v$(node -v | tr -d v)"
            echo "NPM v$(npm -v | tr -d v)"
            echo "Yarn v$(yarn --version | tr -d v)"
      - restore_cache:
          key: emoji-gen/blog/{{ arch }}/{{ checksum "requirements-dev.txt" }}/{{ checksum "yarn.lock" }}/{{ checksum "theme/yarn.lock" }}
      - run:
          name: Install dependencies (Python)
          command: |
            pip3 install -q -r requirements-dev.txt
      - run:
          name: Install dependencies (Node)
          command: |
            yarn
            (cd theme && yarn)

            # for the `save_cache` step
            git checkout yarn.lock
            git checkout theme/yarn.lock
      - run:
          name: Build
          command: |
            make
      - save_cache:
          key: emoji-gen/blog/{{ arch }}/{{ checksum "requirements-dev.txt" }}/{{ checksum "yarn.lock" }}/{{ checksum "theme/yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/workspace/theme/node_modules
            - ~/.cache/yarn/
            - ~/.cache/pip/
      - run:
          name: Deployment
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              yarn global add firebase-tools
              firebase deploy --non-interactive
            fi
